name = "js13k-cloudflare-websocket-example"
main = "src/index.mjs"
compatibility_date = "2023-03-12"
workers_dev = true

[[rules]]
type = "Data"
globs = ["**/*.html"]
fallthrough = false

[durable_objects]
bindings = [
  { name = "servers", class_name = "GameServer" }
]

[[migrations]]
tag = "v1"
new_classes = ["GameServer"]
